apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-oke-sb
spec:
  selector:
    matchLabels:
      app: oci-oke-sb
  replicas: 3
  template:
    metadata:
      labels:
        app: oci-oke-sb
      annotations:
        provider: oracle
    spec:
      containers:
      - image: fra.ocir.io/sehubemeaprod/sbudde/oci-oke-sb:latest
        name: oci-oke-sb
        imagePullPolicy: Always
        ports:
          - name: oci-oke-sb
            containerPort: 8080
            protocol: TCP
        env:
          - name: SPRING_APPLICATION_JSON
            valueFrom:
              configMapKeyRef:
                name: oci-config
                key: oci-config.json 			

      imagePullSecrets:
        - name: ocirsecret

      
